### ISSUE TITLE
support to nested keys 

### ISSUE THREAD

**Issue by GunesYurdakul** [localizely/flutter-intl-vscode#69] opened 2021-05-26 14:11 UTC
.arb files support nested objects like this: 
```
"@login": {
 "@fields": {
    "login": "Login",
    "email": "E-mail",
    "password": "Password",
    "forgot_password": "Forgot password?"  
  },
  "@messages": {
     "error": "xxx"
  }
}
```
However the plugin doesn't generate nested translation objects. Will there be a support for it in the future? Or is there already an existing way to generate nested key value pairs?

**Comment by aleksakrstic** [comment] 2021-06-01 09:56
Hi @GunesYurdakul 
Is it maybe a duplicate of https://github.com/localizely/flutter-intl-vscode/issues/36 ?

**Closed** 2021-06-11 08:24 UTC
